baseurl = "http://kkingori.github.io"
languageCode = "en-us"
title = "KENETH KING'ORI"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
theme = "stanley"
[taxonomies]
	tags = "tags"
